### ISSUE TITLE
Add support for loading Chrome extensions to ManagedBrowser

### ISSUE THREAD

**Issue by wzin** [EndPointCorp/lg_ros_nodes#124]
Child of: https://github.com/EndPointCorp/lg_chef/issues/463

Requirements:
- make managed browser accept a list of paths to extensions on the filesystem
- make it part of metadata attribute in [interactivespaces_msgs.GenericMessage](https://github.com/EndPointCorp/lg_ros_nodes/blob/development/interactivespaces_msgs/README.md) e.g. 
```json
{
"activity_config": {
  "chrome":{
    "extensions":  ["path1", "path2", "path3"]
 }
}
```

Dev notes:
- [ManagedBrowser class](https://github.com/EndPointCorp/lg_ros_nodes/blob/development/lg_common/src/lg_common/managed_browser.py#L27)

**Comment by minshallj** [comment]
After looking into this for a bit, it seems like the only way to load extensions via the command line is to use unpacked extensions. Packed extensions can be installed via the command line, but it seems to take user interaction plus I'm not sure how quick the installation would be if we could find a policy to avoid user interaction.

If we do use unpacked extensions, they'll need to make their way to the display nodes somehow since I haven't been able to load them over http (yet)

**Comment by minshallj** [comment]
![image](https://cloud.githubusercontent.com/assets/2132951/12436173/be3db1c6-bec7-11e5-8eb4-b3e422de5976.png)

**Comment by wzin** [comment]
If it's not merged (yet) then please attach PR here.

**Comment by minshallj** [comment]
pr in #163
